### ISSUE TITLE
Nesting & More

### ISSUE THREAD

**Issue by smooJitter** [axilis/react-native-responsive-layout#24]
Does this support nesting grids?

**Comment by srolija** [comment]
Yes, it does.
In that case, as expected, percentages and fractions are based on component size inside which it is nested.

```jsx
<Grid>
  <Section>
    <Block size="1/2">

      <Grid>
        <Section>
          <Block size="1/2">

            <Text>This is 1/4</Text>

          </Block>
        </Section>
      </Grid>

    </Block>
  </Section>
</Grid>
```

**Comment by smooJitter** [comment]
Sweet! It would be nice if Section had a size prop ( height ) and if both Section and Block had horizontal and vertical alignment props to control how child elements are displayed.  Nevertheless, it appears all of this can be handled via styles.

**Comment by srolija** [comment]
> It would be nice if Section had a size prop ( height )

Originally we planned on having the size of sections as well, however upon implementing typical components we realized there just wasn't the need to do it. 

For example, if you want to implement Header, usually it will contain other elements inside, as well as padding and some style (eg. background color), since you want that component to be reusable it will either have fixed height itself or its height will be based on its child components.

> Section and Block had horizontal and vertical alignment props to control how child elements are displayed 

To make it more flexible for general usage and beginners, there is `stretch` size that when applied to element fill the space as in [this example](https://github.com/axilis/react-native-responsive-layout#centering-and-shifting-elements) enabling aligning on the main axis. The benefit of using those is they can be easily hidden or overriden on different device sizes. While using explicit styles unless injected using wrapper like [withSizeClass](https://github.com/axilis/react-native-responsive-layout/tree/master/docs/api#withsizeclasscomponent--component) would be applied to all devices.

> Nevertheless, it appears all of this can be handled via styles.

You are correct. Styles of all components can be overridden by providing the `style` prop. Also, each component applies only a few styles depending on the how the grid is configured, the source code of components is fairly simple so should you need to, you can find out exactly which styles are applied there.

**Comment by MislavMandaric** [comment]
@smooJitter This is a good question. As @srolija said, it is supported and works as expected. But that is something we should absolutely document in our readme.

We'll add a section on nesting in our readme and release that soon, alongside other changes that are in the pipeline.

**Comment by MislavMandaric** [comment]
We updated our readme with example usage and explanation of nesting behaviour.
