### ISSUE TITLE
center align

### ISSUE THREAD

**Issue by alirezarastegarfard** [axilis/react-native-responsive-layout#37]
i want to have just one element and it be in center not in left
like this 
`      <Section style={{  justifyContent: 'center'}}>
                    <Block xsSize="1/2" smSize="1/4" sizew>
                        <View style={[styles.element, { backgroundColor: '#b2d4fe' }]}>
                            <Text style={styles.text}>Left</Text>
                        </View>
                    </Block>
                </Section>`

**Comment by srolija** [comment]
Generally you wouldn’t change styles of Sections since then you loose control over how they are displayed on different sizes and you override their generated styles depended on grid configuration. Best way would be to use two padding elements, take a look at  Aligning and shifting section of readme, there is link to full example: https://github.com/axilis/react-native-responsive-layout/blob/master/README.md#aligning-and-shifting-elements
